// cshc --gen-stdlib <stdlib directory> <output.csh>
//
// CShift has no way to embed files, so the standard library (stdlib/*.csh) is turned into a CShift source file with
// the texts as string literals (src/Driver/EmbeddedStdlib.csh). The file is generated with this command and checked in;
// tests/run_tests.sh checks that it is up to date. Line ends are normalized to '\n'.

namespace CShift.Driver;

using System;

string HexDigit(int v)
{
    return "0123456789abcdef".Substring(v, 1);
}

// The text as the inside of a string literal.
string EscapeForLiteral(string text)
{
    var sb = StringBuilder.Create();
    for (var i = 0; i < text.Length; i += 1)
    {
        char c = text[i];
        int code = (int)c;
        if (c == '\r')
            continue;
        if (c == '\n')
            sb.Append("\\n");
        else if (c == '\t')
            sb.Append("\\t");
        else if (c == '"')
            sb.Append("\\\"");
        else if (c == '\\')
            sb.Append("\\\\");
        else if (code < 32)
            sb.Append("\\x" + HexDigit(code / 16) + HexDigit(code % 16));
        else
            sb.Append(c);
    }
    return sb.ToString();
}

int GenerateStdlib(string dir, string output)
{
    var files = Directory.FindFiles(dir, ".csh");
    if (files.Count() == 0)
    {
        Console.WriteErrorLine("error: no .csh files in '" + dir + "'");
        return 1;
    }
    var sb = StringBuilder.Create();
    sb.Append("// The standard library (stdlib/*.csh) as string literals. Generated by \"cshc --gen-stdlib stdlib <this file>\"; do not edit.\n\n");
    sb.Append("namespace CShift.Driver;\n\n");
    sb.Append("string[] EmbeddedStdlibNames()\n{\n    return new string[] {\n");
    for (var i = 0; i < files.Count(); i += 1)
        sb.Append("        \"" + Path.GetFileName(files.Get(i)) + "\"" + (i + 1 < files.Count() ? "," : "") + "\n");
    sb.Append("    };\n}\n\n");
    sb.Append("string[] EmbeddedStdlibTexts()\n{\n    var texts = new string[" + files.Count().ToString() + "];\n");
    for (var i = 0; i < files.Count(); i += 1)
    {
        var read = File.ReadAllText(files.Get(i));
        if (read is string text)
        {
            if (text.Length >= 3 && text[0] == (char)0xEF && text[1] == (char)0xBB && text[2] == (char)0xBF)
                text = text.Substring(3);
            sb.Append("    texts[" + i.ToString() + "] = \"" + EscapeForLiteral(text) + "\";\n");
        }
        else
        {
            Console.WriteErrorLine("error: cannot read '" + files.Get(i) + "'");
            return 1;
        }
    }
    sb.Append("    return texts;\n}\n");
    var written = File.WriteAllText(output, sb.ToString());
    if (!written)
    {
        Console.WriteErrorLine("error: cannot write '" + output + "': " + written.Message);
        return 1;
    }
    return 0;
}
