#!/usr/bin/env python3
"""Converts bitmap fonts in BDF format into the font data of System.Ui (stdlib/ui_fonts.csh).

    python tools/ui/bdf2csh.py 7x13.bdf 10x20.bdf > stdlib/ui_fonts.csh

The fonts are the "fixed" fonts of X11 (xorg/font/misc-misc: 7x13.bdf, 10x20.bdf), which are in the public domain
("Public domain font. Share and enjoy."), so programs that embed them owe nobody a notice. Only the characters in
CODES are kept: ASCII, Latin-1 and a few typographic marks and arrows.

Every font becomes three constants: its metrics, the code points (sorted) and the glyphs as one hex string - for each
glyph its rows from top to bottom, every row as many bytes as the cell is wide (most significant bit = leftmost
pixel). A string is one token for the compiler, a slice of numbers would be thousands.
"""

import sys

CODES = (list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)) +
         [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x20AC,
          0x2190, 0x2191, 0x2192, 0x2193, 0x25B2, 0x25B6, 0x25BC, 0x25C0, 0xFFFD])


def read_bdf(path):
    font = {"glyphs": {}}
    with open(path, encoding="latin-1") as f:
        lines = f.read().splitlines()
    i = 0
    while i < len(lines):
        words = lines[i].split()
        i += 1
        if not words:
            continue
        if words[0] == "FONTBOUNDINGBOX":
            font["width"], font["height"], font["x"], font["y"] = map(int, words[1:5])
        elif words[0] == "FONT_ASCENT":
            font["ascent"] = int(words[1])
        elif words[0] == "STARTCHAR":
            code, bbx, rows = None, None, []
            while not lines[i].startswith("ENDCHAR"):
                w = lines[i].split()
                if w[0] == "ENCODING":
                    code = int(w[1])
                elif w[0] == "BBX":
                    bbx = list(map(int, w[1:5]))
                elif w[0] == "BITMAP":
                    i += 1
                    while not lines[i].startswith("ENDCHAR"):
                        rows.append(int(lines[i], 16))
                        i += 1
                    break
                i += 1
            font["glyphs"][code] = (bbx, rows)
    return font


def cell(font, code):
    """The glyph in the font's cell: rows of the cell width, as integers (bit width-1 = leftmost pixel)."""
    width, height = font["width"], font["height"]
    out = [0] * height
    if code not in font["glyphs"]:
        return None
    (w, h, x, y), rows = font["glyphs"][code]
    row_bits = ((w + 7) // 8) * 8
    top = font["ascent"] - (y + h)  # the glyph's first row in the cell
    for r, bits in enumerate(rows):
        cy = top + r
        if not 0 <= cy < height:
            continue
        for b in range(w):
            if bits & (1 << (row_bits - 1 - b)):
                cx = x - font["x"] + b
                if 0 <= cx < width:
                    out[cy] |= 1 << (width - 1 - cx)
    return out


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    print("// The bitmap fonts of System.Ui - generated by tools/ui/bdf2csh.py from the \"fixed\" fonts of X11")
    print("// (xorg/font/misc-misc), which are in the public domain: \"Public domain font. Share and enjoy.\"")
    print("// Do not edit; see the script for the format.")
    print()
    print("namespace System.Ui;")
    for path in sys.argv[1:]:
        font = read_bdf(path)
        name = path.replace("\\", "/").split("/")[-1].rsplit(".", 1)[0]
        width, height = font["width"], font["height"]
        row_bytes = (width + 7) // 8
        codes, hexes = [], []
        for code in CODES:
            rows = cell(font, code)
            if rows is None:
                continue
            codes.append(code)
            for bits in rows:
                bits <<= row_bytes * 8 - width  # left-aligned in its bytes
                hexes.append(format(bits, "0" + str(row_bytes * 2) + "X"))
        print()
        print(f"// {name}: {width} x {height} pixels, the baseline {font['ascent']} rows below the top, {len(codes)} characters.")
        print(f"const int _Font{name}Width = {width};")
        print(f"const int _Font{name}Height = {height};")
        print(f"const int _Font{name}Ascent = {font['ascent']};")
        print(f"const ReadOnlySlice<int> _Font{name}Codes = [")
        for start in range(0, len(codes), 16):
            part = codes[start:start + 16]
            print("    " + ", ".join(f"0x{c:04X}" for c in part) + ("," if start + 16 < len(codes) else ""))
        print("];")
        data = "".join(hexes)
        print(f"const string _Font{name}Bits =")
        line = 112
        chunks = [data[k:k + line] for k in range(0, len(data), line)]
        for k, chunk in enumerate(chunks):
            print(f"    \"{chunk}\"" + (" +" if k + 1 < len(chunks) else ";"))


if __name__ == "__main__":
    main()
